version: '3'
services:
  python-app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Monta el directorio local para permitir cambios en caliente

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - python-app
